# Generated by Django 4.2.7 on 2023-12-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0003_user_age_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_students', to='platform_app.course'),
        ),
    ]
