# Generated by Django 4.2.7 on 2023-12-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0004_student_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
    ]
