# Generated by Django 4.2.7 on 2023-12-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0005_remove_student_enrolled_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(null=True, upload_to='material_fiels'),
        ),
    ]
