# Generated by Django 4.2.7 on 2023-12-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0006_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='platform_app.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='pdf',
            field=models.FileField(null=True, upload_to='assignements'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pdf',
            field=models.FileField(null=True, upload_to='submission'),
        ),
    ]
