# Generated by Django 4.2.7 on 2023-12-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0007_assignment_course_assignment_pdf_submission_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(),
        ),
    ]
